# Generated by Django 5.1.6 on 2025-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('attendees', models.IntegerField()),
                ('ticket_price', models.FloatField()),
                ('past_attendance', models.IntegerField()),
                ('popularity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
